// This file is generated by scripts/generate-built-in-templates.ts.
// Do not edit it by hand.

export interface BuiltInTemplateBundleEntry {
    manifestSource: string;
    files: Array<{ path: string; content: string }>;
}

const builtInTemplates = new Map<string, BuiltInTemplateBundleEntry>([
    [
        "app/chart",
        {
            manifestSource: "{\n    \"kind\": \"app\",\n    \"name\": \"chart\",\n    \"appType\": \"routed\",\n    \"compatibility\": {\n        \"runtimes\": [\"deno\", \"node\"]\n    },\n    \"dependencies\": [\n        {\n            \"specifier\": \"chart.js\",\n            \"registry\": \"npm\",\n            \"package\": \"chart.js\",\n            \"version\": \"^4.5.1\"\n        }\n    ],\n    \"target\": {\n        \"name\": \"{{appName}}\",\n        \"rootDir\": \"{{rootDir}}\",\n        \"appFile\": \"{{rootDir}}/src/app.ts\",\n        \"appId\": \"{{appId}}\",\n        \"outDir\": \"{{outDir}}\"\n    }\n}\n",
            files: [
            {
                path: "index.html.tpl",
                content: "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n        <title>chart</title>\n    </head>\n    <body>\n        <div id=\"app\"></div>\n        <script type=\"module\" src=\"/src/main.tsx\"></script>\n    </body>\n</html>\n",
            },
            {
                path: "src/app.ts.tpl",
                content: "import { defineApp } from \"mainz\";\nimport { HomePage } from \"./pages/Home.page.tsx\";\nimport { NotFoundPage } from \"./pages/NotFound.page.tsx\";\n\nexport const app = defineApp({\n    id: \"{{appId}}\",\n    navigation: \"{{appNavigation}}\",\n    pages: [HomePage],\n    notFound: NotFoundPage,\n});\n",
            },
            {
                path: "src/charts/categoriesPieChartConfig.ts.tpl",
                content: "import type { ChartConfiguration } from \"chart.js\";\n\nexport const categoriesPieChartConfig: ChartConfiguration = {\n    type: \"pie\",\n    data: {\n        labels: [\"Electronics\", \"Clothing\", \"Home\", \"Books\", \"Other\"],\n        datasets: [\n            {\n                label: \"Categories\",\n                data: [35, 25, 20, 10, 10],\n            },\n        ],\n    },\n    options: {\n        responsive: true,\n        maintainAspectRatio: false,\n        plugins: {\n            legend: {\n                position: \"bottom\",\n            },\n        },\n    },\n};\n",
            },
            {
                path: "src/components/ChartWidget.tsx.tpl",
                content: "import { Component } from \"mainz\";\nimport Chart from \"chart.js/auto\";\nimport type { ChartConfiguration } from \"chart.js\";\n\ninterface ChartCardProps {\n    title: string;\n    description?: string;\n    config: ChartConfiguration;\n}\n\nexport class ChartWidget extends Component<ChartCardProps> {\n    private chart?: Chart;\n\n    override onMount() {\n        this.createChart();\n    }\n\n    override onUnmount() {\n        this.chart?.destroy();\n        this.chart = undefined;\n    }\n\n    private createChart() {\n        const canvas = this.querySelector<HTMLCanvasElement>(\"[data-chart]\");\n\n        if (!canvas) return;\n\n        this.chart?.destroy();\n        this.chart = new Chart(canvas, this.props.config);\n    }\n\n    override render() {\n        return (\n            <article>\n                <header>\n                    <h2>{this.props.title}</h2>\n\n                    {this.props.description && (\n                        <p>\n                            {this.props.description}\n                        </p>\n                    )}\n                </header>\n\n                <div>\n                    <canvas data-chart></canvas>\n                </div>\n            </article>\n        );\n    }\n}\n",
            },
            {
                path: "src/main.tsx.tpl",
                content: "import { startApp } from \"mainz\";\nimport { app } from \"./app.ts\";\n\nstartApp(app, {\n    mount: \"#app\",\n});\n",
            },
            {
                path: "src/pages/Home.page.tsx.tpl",
                content: "import { Page, Route } from \"mainz\";\nimport { ChartWidget } from \"../components/ChartWidget.tsx\";\nimport { categoriesPieChartConfig } from \"../charts/categoriesPieChartConfig.ts\";\n\n@Route(\"/\")\nexport class HomePage extends Page {\n    override head() {\n        return {\n            title: \"chart\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <header>\n                    <h1>chart</h1>\n                    <p>Mainz + Chart.js</p>\n                </header>\n\n                <ChartWidget\n                    title=\"Sales by category\"\n                    config={categoriesPieChartConfig}\n                />\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "src/pages/NotFound.page.tsx.tpl",
                content: "import { Page } from \"mainz\";\n\nexport class NotFoundPage extends Page {\n    override head() {\n        return {\n            title: \"404 | chart\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>Page not found</h1>\n                <a href=\"/\">Go home</a>\n            </main>\n        );\n    }\n}\n",
            },
            ],
        },
    ],
    [
        "app/default-root",
        {
            manifestSource: "{\n    \"kind\": \"app\",\n    \"name\": \"default-root\",\n    \"appType\": \"root\",\n    \"target\": {\n        \"name\": \"{{appName}}\",\n        \"rootDir\": \"{{rootDir}}\",\n        \"appFile\": \"{{rootDir}}/src/app.ts\",\n        \"appId\": \"{{appId}}\",\n        \"outDir\": \"{{outDir}}\"\n    }\n}\n",
            files: [
            {
                path: "index.html.tpl",
                content: "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n        <title>{{appTitle}}</title>\n    </head>\n    <body>\n        <div id=\"app\"></div>\n        <script type=\"module\" src=\"/src/main.tsx\"></script>\n    </body>\n</html>\n",
            },
            {
                path: "src/app.ts.tpl",
                content: "import { defineApp } from \"mainz\";\nimport { AppRoot } from \"./AppRoot.tsx\";\n\nexport const app = defineApp({\n    id: \"{{appId}}\",\n    root: AppRoot,\n});\n",
            },
            {
                path: "src/AppRoot.tsx.tpl",
                content: "import { Component } from \"mainz\";\n\nexport class AppRoot extends Component {\n    override render() {\n        return (\n            <main>\n                <h1>{{appTitle}}</h1>\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "src/main.tsx.tpl",
                content: "import { startApp } from \"mainz\";\nimport { app } from \"./app.ts\";\n\nstartApp(app, {\n    mount: \"#app\",\n});\n",
            },
            ],
        },
    ],
    [
        "app/default-routed",
        {
            manifestSource: "{\n    \"kind\": \"app\",\n    \"name\": \"default-routed\",\n    \"appType\": \"routed\",\n    \"target\": {\n        \"name\": \"{{appName}}\",\n        \"rootDir\": \"{{rootDir}}\",\n        \"appFile\": \"{{rootDir}}/src/app.ts\",\n        \"appId\": \"{{appId}}\",\n        \"outDir\": \"{{outDir}}\"\n    }\n}\n",
            files: [
            {
                path: "index.html.tpl",
                content: "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n        <title>{{appTitle}}</title>\n    </head>\n    <body>\n        <div id=\"app\"></div>\n        <script type=\"module\" src=\"/src/main.tsx\"></script>\n    </body>\n</html>\n",
            },
            {
                path: "src/app.ts.tpl",
                content: "import { defineApp } from \"mainz\";\nimport { HomePage } from \"./pages/Home.page.tsx\";\nimport { NotFoundPage } from \"./pages/NotFound.page.tsx\";\n\nexport const app = defineApp({\n    id: \"{{appId}}\",\n    navigation: \"{{appNavigation}}\",\n    pages: [HomePage],\n    notFound: NotFoundPage,\n});\n",
            },
            {
                path: "src/main.tsx.tpl",
                content: "import { startApp } from \"mainz\";\nimport { app } from \"./app.ts\";\n\nstartApp(app, {\n    mount: \"#app\",\n});\n",
            },
            {
                path: "src/pages/Home.page.tsx.tpl",
                content: "import { Page, Route } from \"mainz\";\n\n@Route(\"/\")\nexport class HomePage extends Page {\n    override head() {\n        return {\n            title: \"{{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>{{appTitle}}</h1>\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "src/pages/NotFound.page.tsx.tpl",
                content: "import { Page } from \"mainz\";\n\nexport class NotFoundPage extends Page {\n    override head() {\n        return {\n            title: \"404 | {{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>Page not found</h1>\n                <a href=\"/\">Go home</a>\n            </main>\n        );\n    }\n}\n",
            },
            ],
        },
    ],
    [
        "project/deno/empty",
        {
            manifestSource: "{\n    \"kind\": \"project\",\n    \"name\": \"empty\",\n    \"runtime\": \"deno\"\n}\n",
            files: [
            {
                path: "deno.json.tpl",
                content: "{\n    \"compilerOptions\": {\n        \"lib\": [\"dom\", \"esnext\"],\n        \"jsx\": \"react-jsx\",\n        \"jsxImportSource\": \"mainz\",\n        \"strict\": true\n    },\n    \"imports\": {\n        \"@deno/vite-plugin\": \"npm:@deno/vite-plugin@2.0.2\",\n        \"mainz\": \"{{mainzSpecifier}}\",\n        \"mainz/\": \"{{mainzSubpathPrefix}}\",\n        \"vite\": \"npm:vite@8.0.10\"\n    },\n    \"tasks\": {\n        \"dev\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} dev\",\n        \"build\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} build\",\n        \"preview\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} preview\",\n        \"test\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} test\",\n        \"publish-info\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} publish-info\",\n        \"diagnose\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} diagnose\"\n    }\n}\n",
            },
            {
                path: "mainz.config.ts.tpl",
                content: "import { defineMainzConfig } from \"mainz/config\";\n\nexport default defineMainzConfig({\n    runtime: \"deno\",\n    targets: [\n    ],\n});\n",
            },
            ],
        },
    ],
    [
        "project/deno/starter",
        {
            manifestSource: "{\n    \"kind\": \"project\",\n    \"name\": \"starter\",\n    \"runtime\": \"deno\"\n}\n",
            files: [
            {
                path: "app/deno.json.tpl",
                content: "{\n    \"imports\": {}\n}\n",
            },
            {
                path: "app/index.html.tpl",
                content: "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n        <title>{{appTitle}}</title>\n    </head>\n    <body>\n        <div id=\"app\"></div>\n        <script type=\"module\" src=\"/src/main.tsx\"></script>\n    </body>\n</html>\n",
            },
            {
                path: "app/src/app.ts.tpl",
                content: "import { defineApp } from \"mainz\";\nimport { HomePage } from \"./pages/Home.page.tsx\";\nimport { NotFoundPage } from \"./pages/NotFound.page.tsx\";\n\nexport const app = defineApp({\n    id: \"{{appId}}\",\n    navigation: \"{{appNavigation}}\",\n    pages: [HomePage],\n    notFound: NotFoundPage,\n});\n",
            },
            {
                path: "app/src/components/Counter.tsx.tpl",
                content: "import { Component } from \"mainz\";\n\ntype CounterState = {\n    count: number;\n};\n\nexport class Counter extends Component<{}, CounterState> {\n    protected override initState(): CounterState {\n        return { count: 0 };\n    }\n\n    private decrement = () => {\n        this.setState({ count: this.state.count - 1 });\n    };\n\n    private increment = () => {\n        this.setState({ count: this.state.count + 1 });\n    };\n\n    override render() {\n        return (\n            <section className=\"counter\" aria-label=\"Counter example\">\n                <p>Count: {this.state.count}</p>\n                <div>\n                    <button type=\"button\" onClick={this.decrement}>-</button>\n                    <button type=\"button\" onClick={this.increment}>+</button>\n                </div>\n            </section>\n        );\n    }\n}\n",
            },
            {
                path: "app/src/main.tsx.tpl",
                content: "import { startApp } from \"mainz\";\nimport { app } from \"./app.ts\";\n\nstartApp(app, {\n    mount: \"#app\",\n});\n",
            },
            {
                path: "app/src/pages/Home.page.tsx.tpl",
                content: "import { Page, Route } from \"mainz\";\nimport { Counter } from \"../components/Counter.tsx\";\n\n@Route(\"/\")\nexport class HomePage extends Page {\n    override head() {\n        return {\n            title: \"{{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>{{appTitle}}</h1>\n                <p>Welcome to your Mainz starter app.</p>\n                <Counter />\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "app/src/pages/NotFound.page.tsx.tpl",
                content: "import { Page } from \"mainz\";\n\nexport class NotFoundPage extends Page {\n    override head() {\n        return {\n            title: \"404 | {{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>Page not found</h1>\n                <a href=\"/\">Go home</a>\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "deno.json.tpl",
                content: "{\n    \"compilerOptions\": {\n        \"lib\": [\"dom\", \"esnext\"],\n        \"jsx\": \"react-jsx\",\n        \"jsxImportSource\": \"mainz\",\n        \"strict\": true\n    },\n    \"imports\": {\n        \"@deno/vite-plugin\": \"npm:@deno/vite-plugin@2.0.2\",\n        \"mainz\": \"{{mainzSpecifier}}\",\n        \"mainz/\": \"{{mainzSubpathPrefix}}\",\n        \"vite\": \"npm:vite@8.0.10\"\n    },\n    \"tasks\": {\n        \"dev\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} dev\",\n        \"build\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} build\",\n        \"preview\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} preview\",\n        \"test\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} test\",\n        \"publish-info\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} publish-info\",\n        \"diagnose\": \"deno run -A --config {{denoConfigPath}} {{mainzCliSpecifier}} diagnose\"\n    },\n    \"workspace\": [\n        \"./app\"\n    ]\n}\n",
            },
            {
                path: "mainz.config.ts.tpl",
                content: "import { defineMainzConfig } from \"mainz/config\";\n\nexport default defineMainzConfig({\n    runtime: \"deno\",\n    targets: [\n        {\n            name: \"{{appName}}\",\n            rootDir: \"{{rootDir}}\",\n            appFile: \"{{rootDir}}/src/app.ts\",\n            appId: \"{{appId}}\",\n            outDir: \"{{outDir}}\",\n        },\n    ],\n});\n",
            },
            ],
        },
    ],
    [
        "project/node/empty",
        {
            manifestSource: "{\n    \"kind\": \"project\",\n    \"name\": \"empty\",\n    \"runtime\": \"node\"\n}\n",
            files: [
            {
                path: ".npmrc.tpl",
                content: "@jsr:registry=https://npm.jsr.io\n",
            },
            {
                path: "mainz.config.ts.tpl",
                content: "import { defineMainzConfig } from \"mainz/config\";\n\nexport default defineMainzConfig({\n    runtime: \"node\",\n    targets: [\n    ],\n});\n",
            },
            {
                path: "package.json.tpl",
                content: "{\n    \"name\": \"{{projectName}}\",\n    \"private\": true,\n    \"type\": \"module\",\n    \"scripts\": {\n        \"dev\": \"mainz dev\",\n        \"build\": \"mainz build\",\n        \"preview\": \"mainz preview\",\n        \"test\": \"mainz test\",\n        \"diagnose\": \"mainz diagnose\"\n    },\n    \"dependencies\": {\n        \"mainz\": \"{{mainzSpecifier}}\"\n    },\n    \"devDependencies\": {\n        \"vite\": \"^8.0.10\"\n    }\n}\n",
            },
            {
                path: "tsconfig.json.tpl",
                content: "{\n    \"compilerOptions\": {\n        \"target\": \"ES2022\",\n        \"module\": \"ESNext\",\n        \"moduleResolution\": \"Bundler\",\n        \"lib\": [\"DOM\", \"ES2022\"],\n        \"jsx\": \"react-jsx\",\n        \"jsxImportSource\": \"mainz\",\n        \"experimentalDecorators\": true,\n        \"useDefineForClassFields\": false,\n        \"strict\": true,\n        \"noEmit\": true,\n        \"allowImportingTsExtensions\": true,\n        \"types\": []\n    },\n    \"include\": [\"**/*.ts\", \"**/*.tsx\"]\n}\n",
            },
            ],
        },
    ],
    [
        "project/node/starter",
        {
            manifestSource: "{\n    \"kind\": \"project\",\n    \"name\": \"starter\",\n    \"runtime\": \"node\"\n}\n",
            files: [
            {
                path: ".npmrc.tpl",
                content: "@jsr:registry=https://npm.jsr.io\n",
            },
            {
                path: "app/index.html.tpl",
                content: "<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n        <title>{{appTitle}}</title>\n    </head>\n    <body>\n        <div id=\"app\"></div>\n        <script type=\"module\" src=\"/src/main.tsx\"></script>\n    </body>\n</html>\n",
            },
            {
                path: "app/package.json.tpl",
                content: "{\n    \"name\": \"{{appName}}\",\n    \"private\": true,\n    \"type\": \"module\"\n}\n",
            },
            {
                path: "app/src/app.ts.tpl",
                content: "import { defineApp } from \"mainz\";\nimport { HomePage } from \"./pages/Home.page.tsx\";\nimport { NotFoundPage } from \"./pages/NotFound.page.tsx\";\n\nexport const app = defineApp({\n    id: \"{{appId}}\",\n    navigation: \"{{appNavigation}}\",\n    pages: [HomePage],\n    notFound: NotFoundPage,\n});\n",
            },
            {
                path: "app/src/components/Counter.tsx.tpl",
                content: "import { Component } from \"mainz\";\n\ntype CounterState = {\n    count: number;\n};\n\nexport class Counter extends Component<{}, CounterState> {\n    protected override initState(): CounterState {\n        return { count: 0 };\n    }\n\n    private decrement = () => {\n        this.setState({ count: this.state.count - 1 });\n    };\n\n    private increment = () => {\n        this.setState({ count: this.state.count + 1 });\n    };\n\n    override render() {\n        return (\n            <section className=\"counter\" aria-label=\"Counter example\">\n                <p>Count: {this.state.count}</p>\n                <div>\n                    <button type=\"button\" onClick={this.decrement}>-</button>\n                    <button type=\"button\" onClick={this.increment}>+</button>\n                </div>\n            </section>\n        );\n    }\n}\n",
            },
            {
                path: "app/src/main.tsx.tpl",
                content: "import { startApp } from \"mainz\";\nimport { app } from \"./app.ts\";\n\nstartApp(app, {\n    mount: \"#app\",\n});\n",
            },
            {
                path: "app/src/pages/Home.page.tsx.tpl",
                content: "import { Page, Route } from \"mainz\";\nimport { Counter } from \"../components/Counter.tsx\";\n\n@Route(\"/\")\nexport class HomePage extends Page {\n    override head() {\n        return {\n            title: \"{{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>{{appTitle}}</h1>\n                <p>Welcome to your Mainz starter app.</p>\n                <Counter />\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "app/src/pages/NotFound.page.tsx.tpl",
                content: "import { Page } from \"mainz\";\n\nexport class NotFoundPage extends Page {\n    override head() {\n        return {\n            title: \"404 | {{appTitle}}\",\n        };\n    }\n\n    override render() {\n        return (\n            <main>\n                <h1>Page not found</h1>\n                <a href=\"/\">Go home</a>\n            </main>\n        );\n    }\n}\n",
            },
            {
                path: "mainz.config.ts.tpl",
                content: "import { defineMainzConfig } from \"mainz/config\";\n\nexport default defineMainzConfig({\n    runtime: \"node\",\n    targets: [\n        {\n            name: \"{{appName}}\",\n            rootDir: \"{{rootDir}}\",\n            appFile: \"{{rootDir}}/src/app.ts\",\n            appId: \"{{appId}}\",\n            outDir: \"{{outDir}}\",\n        },\n    ],\n});\n",
            },
            {
                path: "package.json.tpl",
                content: "{\n    \"name\": \"{{projectName}}\",\n    \"private\": true,\n    \"type\": \"module\",\n    \"scripts\": {\n        \"dev\": \"mainz dev\",\n        \"build\": \"mainz build\",\n        \"preview\": \"mainz preview\",\n        \"test\": \"mainz test\",\n        \"diagnose\": \"mainz diagnose\"\n    },\n    \"dependencies\": {\n        \"mainz\": \"{{mainzSpecifier}}\"\n    },\n    \"devDependencies\": {\n        \"vite\": \"^8.0.10\"\n    },\n    \"workspaces\": [\n        \"app\"\n    ]\n}\n",
            },
            {
                path: "tsconfig.json.tpl",
                content: "{\n    \"compilerOptions\": {\n        \"target\": \"ES2022\",\n        \"module\": \"ESNext\",\n        \"moduleResolution\": \"Bundler\",\n        \"lib\": [\"DOM\", \"ES2022\"],\n        \"jsx\": \"react-jsx\",\n        \"jsxImportSource\": \"mainz\",\n        \"experimentalDecorators\": true,\n        \"useDefineForClassFields\": false,\n        \"strict\": true,\n        \"noEmit\": true,\n        \"allowImportingTsExtensions\": true,\n        \"types\": []\n    },\n    \"include\": [\"**/*.ts\", \"**/*.tsx\"]\n}\n",
            },
            ],
        },
    ],
    [
        "workflow/gh-pages",
        {
            manifestSource: "{\n    \"kind\": \"workflow\",\n    \"name\": \"gh-pages\"\n}\n",
            files: [
            {
                path: ".github/workflows/deploy-github-pages.yml.tpl",
                content: "name: Deploy to GitHub Pages\n\n{{triggerBlock}}\n\npermissions:\n    contents: read\n    pages: write\n    id-token: write\n\nconcurrency:\n    group: pages\n    cancel-in-progress: true\n\njobs:\n    build:\n        runs-on: ubuntu-latest\n        steps:\n            - name: Checkout\n              uses: actions/checkout@v4\n\n            - name: Setup Deno\n              uses: denoland/setup-deno@v2\n              with:\n                  deno-version: v2.x\n\n{{buildSteps}}\n\n            - name: Resolve publish metadata and assemble Pages artifact\n              id: publish\n              shell: bash\n              run: |\n{{metadataCommands}}\n{{metadataEchoes}}\n{{artifactCommands}}\n                  staging_dir=\"_pages\"\n\n                  rm -rf \"$staging_dir\"\n                  mkdir -p \"$staging_dir\"\n{{stagingCommands}}\n\n                  echo \"artifact_dir=$staging_dir\" >> \"$GITHUB_OUTPUT\"\n\n            - name: Upload Pages artifact\n              uses: actions/upload-pages-artifact@v3\n              with:\n                  path: ${{ steps.publish.outputs.artifact_dir }}\n\n    deploy:\n        needs: build\n        runs-on: ubuntu-latest\n        environment:\n            name: github-pages\n            url: ${{ steps.deployment.outputs.page_url }}\n        steps:\n            - name: Deploy to GitHub Pages\n              id: deployment\n              uses: actions/deploy-pages@v4\n",
            },
            ],
        },
    ],
]);

export function listBuiltInTemplateBundleKeys(): string[] {
    return [...builtInTemplates.keys()];
}

export function resolveBuiltInTemplateBundle(kind: string, name: string): BuiltInTemplateBundleEntry | undefined {
    return builtInTemplates.get(`${kind}/${name}`.replaceAll("\\", "/"));
}
